Create Public User Page
battlecode/galaxy pull request #369
Opened 2022-12-03 20:45 UTC by lowtorola

Resolves #19 by creating a bare-bones public user page utilizing the existing `userCard` and `teamCard` components. Draft for now, work incoming :rocket:!

2022-12-07 02:33 UTC, n8kim1 commented
cross-checked other examples, and noticed braces instead of parens. Not 100% sure why that fixes but it fixes! I think because in braces, it was treating as code (so, like, the line just declares a component, but outputs nothing / silently drops it). 
Anyways there's new errors but you should be able to see them now in console etc

2022-12-13 00:16 UTC, n8kim1 commented
Frontend looks good! However, explicitly tagging @j-mao for backend review, so I'll hold off on clicking the approve button for now
(would tag gaurav too but don't wanna give him too much on his plate during these times)

Have a couple small things to fix, but they're nowhere close to as urgent as other p1 things. So I'll file follow-up issues and we can just focus on more pressing work

2022-12-13 01:17 UTC, j-mao requested changes
I think this looks great! One thing I'm a bit queasy about, though, is the whole extra viewset… would it be possible to move the `teams` method into the existing `UserViewSet`? Please let me know / comment in code if there was a specific reason this isn't possible.

Perhaps this is achievable by:
- Moving the entire `teams` method over/
- Setting `detail=True`. Then, you'll receive the user ID directly as a kwarg `pk`.
- Instead of using `self.get_queryset()` in `teams`, you can use `Team.objects.all()` directly. Perhaps even filter to `Team.objects.all().visible()` depending on whether `request.user` is staff.

2022-12-13 01:17 UTC, j-mao commented on backend/siarnaq/api/user/views.py
> +        permission_classes=(IsAuthenticated,),
Would `AllowAny` be enough here? I think non-logged-in people can also be allowed to see team memberships.

2022-12-13 02:20 UTC, lowtorola commented
Thanks Jerry! I struggled for at least a day trying to get the endpoint under the UserViewSet... the `pk` kwarg hint solved it!

2022-12-13 03:09 UTC, j-mao approved these changes
Looks good to me! Just pushed a small commit to lint.

2022-12-13 03:19 UTC, merged