Delete inactive teams with no submissions.
battlecode/galaxy pull request #390
Opened 2022-12-11 03:12 UTC by apollo1291

fixes Issue #363. deletes empty teams that have no submissions once the last user leaves. Does not delete teams that already have no users.

2022-12-11 21:34 UTC, gaurav-arya commented
Should this still be a draft or marked ready for review?

2022-12-13 16:40 UTC, gaurav-arya requested changes
Looks good to me other than one nit!

2022-12-14 01:32 UTC, apollo1291 commented on backend/siarnaq/api/teams/signals.py
>  def make_empty_team_inactive(instance, action, **kwargs):
should this function name change?

2022-12-21 03:50 UTC, gaurav-arya commented on backend/siarnaq/api/teams/signals.py
>  def make_empty_team_inactive(instance, action, **kwargs):
Sure, how about `handle_empty_team`?

2022-12-21 16:32 UTC, gaurav-arya submitted a review, later dismissed
Looks good to me! Let's get a review from @j-mao

2022-12-25 10:40 UTC, j-mao requested changes
This is almost good to go! Gave it a whirl and encountered a small bug that need fixing.

You'll likely also need to  change `TeamProfile.team` to have `on_delete=models.CASCADE` (instead of `PROTECT`). The reason is, "protect" will block deleting anything that has a profile attached, while "cascade" will delete any attached profiles. After this change, you might need to generate a new *migration* (this tells the database there's an update to the models): the command is `./manage.py makemigrations`, but feel free to give a yell in slack if something funky happens.

Once it's fixed and it's tested+working, feel free to send through another review! :')

2022-12-25 10:40 UTC, j-mao commented on backend/siarnaq/api/teams/signals.py
> +            if not instance.has_active_submissions():
typo
```suggestion
            if not instance.has_active_submission():
```

2023-01-01 00:18 UTC, gaurav-arya approved these changes
Looks good to me! Wait for a re-review from @j-mao to merge. Also make sure to live test the latest version to ensure no silly typos:)

2023-01-01 01:30 UTC, j-mao approved these changes
Looks good to go!

2023-01-01 11:32 UTC, merged