Show submission history
battlecode/galaxy pull request #416
Opened 2022-12-28 02:36 UTC by n8kim1

2022-12-29 12:47 UTC, j-mao reviewed
Looks like it works. A couple questions:

- How does pagination work? Perhaps I'm missing something, but it seems like the code is hardwired to fetch page 1.
- Shall we also show the submitted package name?

2022-12-29 14:43 UTC, gaurav-arya approved these changes
Agree w/ Jerry's comment. Also, a small thing, but after clicking the refresh button, the button stays dark for some reason

2022-12-31 10:56 UTC, gaurav-arya requested changes
Bug from live testing:

- If I upload a submission, submit it, and then try to submit a new file without refreshing the page, the file upload does not work (it keeps saying "no file chosen").
- After uploading one submission, if I click choose file with the intention of uploading a second one, but then escape the file upload window instead, the page crashes.

2023-01-01 01:36 UTC, j-mao submitted a review, later dismissed

2023-01-01 03:52 UTC, j-mao approved these changes

2023-01-02 04:21 UTC, merged