Fix Long Usernames on Team Card
battlecode/galaxy pull request #420
Opened 2022-12-29 03:14 UTC by lowtorola

Resolves #347
- Trimmed usernames to a maximum of 21 characters on `TeamCard` (arbitrary by what looked good)
- Added newline after each user
- Aligned users to left and added a lil padding for aesthetics

2022-12-29 07:32 UTC, n8kim1 submitted a review, later dismissed

2022-12-29 07:32 UTC, n8kim1 commented
Looks good!
Your call abt this one, cuz it's high-effort: maybe, for padded names, include a "..." at the end? Perhaps that reduces user confusion

2023-01-04 01:23 UTC, gaurav-arya requested changes
Agree with @n8kim1 about `...`'s for spliced names

2023-01-04 01:33 UTC, gaurav-arya commented
Could we also do something for the rankings page? See below:
![image](https://user-images.githubusercontent.com/43899491/210468148-8e774a17-55bf-42ef-a69a-059d7ef21da0.png)

And make sure to test this on mobile screens too (you can test this using the developer tools on your browser, e.g. for chrome: https://developer.chrome.com/docs/devtools/device-mode/)

2023-01-06 06:15 UTC, gaurav-arya approved these changes

2023-01-06 06:17 UTC, gaurav-arya requested changes
Actually, could we put the `trimUsername` function into a `utils/misc.js` file to avoid repeating it?

2023-01-08 03:53 UTC, gaurav-arya approved these changes

2023-01-08 03:54 UTC, gaurav-arya requested changes

2023-01-08 03:54 UTC, gaurav-arya commented on frontend/src/utils/misc.js
> +export function trimUsername(username, length) {
For consistency, could we remove `export` here and add `export {trim username}` to the bottom of the file?

2023-01-08 04:23 UTC, gaurav-arya approved these changes

2023-01-08 04:23 UTC, merged