Basecard header
battlecode/galaxy pull request #654
Opened 2023-06-24 01:01 UTC by apollo1291

Add a BaseCard, component, And a Header component. (Header for year Display page)

2023-06-25 01:42 UTC, acrantel requested changes

2023-06-25 01:42 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +const Header = ({loggedIn, logoPath}: headerProps): JSX.Element => {
for this too, let's be consistent with how we defined basecard
`const BaseCard: React.FC<BaseCardProps> = ({ GameImage, GameName, GameDescr, GameYear }) => {`

2023-06-25 01:42 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +interface headerProps {
```suggestion
interface HeaderProps {
```
for consistency

2023-06-25 01:42 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +    loggedIn: boolean
This is OK for now, we will switch to a context for user information later

2023-06-25 01:57 UTC, acrantel commented on frontend2/src/components/BaseCard.tsx
> +  GameImage: string;
let's change all these properties to camelCase

`GameImage` => `gameImage`

etc

2023-07-02 19:20 UTC, acrantel commented
https://tailwindui.com/components/application-ui/application-shells/stacked

2023-08-20 17:21 UTC, acrantel commented on frontend2/src/battlecode-logo-horiz-white.png
this file doesn't belong in the src folder, all images should go in the `frontend2/public` folder

2023-08-20 17:32 UTC, acrantel requested changes
thanks for tackling this! headers are super complicated

I put this in comments but also wanted to mention it here; images should live in the `frontend2/public` directory. When you want to reference it in code, you just need to use `/<image_name_with_extension>` to display it

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/BaseCard.tsx
> +        <img className="object-cover" src={require(`../${gameImage}`)} alt={gameName} />
```suggestion
        <img className="object-cover" src={gameImage} alt={gameName} />
```
you don't need the require() here

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +              <img className="h-8 w-auto" src={require(`../${logoPath}`)} alt="Battlecode" />
similar to above, you don't need the require here.

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +        {/* <div className="flex space-x-4">
delete these big comments of code if we don't need them

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +            </button>
This notification button doesn't seem to do anything right now, let's remove it.

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +            </a>
We don't have a settings page right now, let's remove this

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +// const Header: React.FC<headerProps> = ({loggedIn, logoPath}): JSX.Element => {
Let's delete this big comment if it's unused.

2023-08-20 17:32 UTC, acrantel commented on frontend2/src/components/Header.tsx
> +              src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
This is OK to keep for this PR. Eventually, we will want to fetch the user avatar and put it here instead.

2023-08-29 20:10 UTC, lowtorola approved these changes
LGTM! 🎉

2023-08-29 20:58 UTC, merged