Scrimmaging Page
battlecode/galaxy pull request #677
Opened 2023-09-12 21:30 UTC by lowtorola

Adds a scrimmaging page!

2023-09-13 14:25 UTC, lowtorola commented on frontend2/src/views/Scrimmaging.tsx
> +      );
Todo: need to send this to the state!

2023-09-13 14:26 UTC, lowtorola commented on frontend2/src/views/Scrimmaging.tsx
> +            setQueryParams({ ...queryParams, scrimsPage: "1" });
switch these so the if statement goes first and then returns!

2023-09-13 14:29 UTC, lowtorola commented on frontend2/src/views/Scrimmaging.tsx
> +              pageSize={10}
should make this an optional prop in `BattlecodeTableBottomElement.tsx` and default to 10. Maybe even don't allow this to be changed and add page sizing to be changed in db calls in a future PR?

2023-09-26 19:48 UTC, lowtorola commented
TODO: request scrimmages against a team and implement "incoming scrimmage requests" section

2023-09-30 19:49 UTC, lowtorola commented
Convo at meeting 9/30:
- Want to refactor `BattlecodeTable` usages into e.g. `RecentTournamentMatchesTable.tsx`
- ^^ will require new subfolders e.g. `Scrimaging` in `components`
- Want to refactor new `InboxOutbox` component
- Move fetch functions into useEffects, set loading above functions, and use destructors to prevent race conditions (see EpisodeProvider)

2023-10-03 18:13 UTC, lowtorola commented on frontend2/src/views/Scrimmaging.tsx
> +              pageSize={10}
TODO in future PR

2023-10-03 19:38 UTC, lowtorola commented
In order to be truly done, this page will need the following dialogs/buttons:
- [ ] ACCEPT scrimmage
- [ ] REJECT scrimmage
- [ ] CANCEL scrimmage
- [ ] match replay button

2023-10-04 19:24 UTC, acrantel requested changes
Great work! Left some comments mostly regarding code readability / organization

I think we briefly discussed this on Tuesday, but I just realized that using `setSearchParams` in `Scrimmaging.tsx` will cause the entire page to rerender b/c searchParams changes. 
This issue has more discussion about this rerendering issue: https://github.com/remix-run/react-router/issues/8908

I believe you mentioned that we can directly update window.history instead of using setSearchParams, and I think this would avoid the rerendering issue.

2023-10-04 19:24 UTC, acrantel commented on frontend2/src/views/Scrimmaging.tsx
> +  }
nit: move this interface definition outside the component function b/c it doesn't depend on component state

2023-10-04 19:24 UTC, acrantel commented on frontend2/src/views/Scrimmaging.tsx
> +  }, [queryParams.inboxPage]);
All of these useEffects also depend on episodeId, so we should add that into the dependencies

2023-10-04 19:24 UTC, acrantel commented on frontend2/src/views/Scrimmaging.tsx
> +      tourneyPage: parseInt(searchParams.get("tourneyPage") ?? "1"),
nit: we can reduce repetition here by using a small function 
`const parsePageParam = (paramName: string) => parseInt(searchParams.get(paramName) ?? "1");`

2023-10-18 23:10 UTC, acrantel commented on frontend2/src/components/compete/MatchScore.tsx
> +  userTeamId?: number;
ignore this comment, userTeamId may not be the current user's team

2023-10-19 00:00 UTC, acrantel approved these changes
This is awesome! Just left two minor requests for change, but once those are addressed feel free to merge

2023-10-21 18:45 UTC, merged