Sri/jointeam
battlecode/galaxy pull request #705
Opened 2023-11-27 21:51 UTC by sri240

Created "My Team" page for when users are not in a team, allowing for team creation and joining a team.

2023-11-28 18:09 UTC, lowtorola requested changes
Looks great! Should be good to re-request for merging after the few nits I commented. Also, can you send a screenshot of what the page looks like to the PR (just for my own curiosity)? 🎉

2023-11-28 18:21 UTC, acrantel reviewed
great work! as Lowell said, you should run `npm run format` in the frontend2 folder to format everything nicely

2023-11-28 18:21 UTC, acrantel commented on frontend2/src/components/team/EligibilitySettings.tsx
> +    return <div></div>;
We can place the string `Error: You're not in a team!` inside the div here to display it

2023-12-02 19:30 UTC, sri240 commented
<img width="1440" alt="Screenshot 2023-12-02 at 2 29 49 PM" src="https://github.com/battlecode/galaxy/assets/27715871/e953ecc7-1a2c-40eb-aa34-b0b9ad6662be">

2023-12-02 20:18 UTC, acrantel commented
lgtm! nice work 🥳

2023-12-02 20:19 UTC, acrantel approved these changes

2023-12-05 20:09 UTC, merged