Add file downloads
battlecode/galaxy pull request #804
Opened 2024-05-11 21:07 UTC by nicolexxuu

Closes #792

2024-06-14 00:55 UTC, lowtorola requested changes
@nicolexxuu Lmk if this review helps!

2024-06-14 00:55 UTC, lowtorola commented on frontend2/src/views/Account.tsx
> +    await downloadResume.mutateAsync({ id: user?.id ?? 0 });
See #809, we are moving away from mutateAsync in favor of mutate 😎

2024-06-14 00:55 UTC, lowtorola commented on frontend2/src/views/Account.tsx
> +    await downloadResume.mutateAsync({ id: user?.id ?? 0 });
nit: prefer disabling the button if user isn't loaded, as I'm not sure if our db would successfully reject for a request to id 0 by default. Then we could block the event via a if conditional if not loaded, lmk if this makes sense.

2024-07-04 16:35 UTC, nicolexxuu commented
should I implement avatar file downloads as well? 
also npm run lint still doesn't work for me ☹️

2024-07-10 01:46 UTC, lowtorola requested changes
Looks good, nice job! I would say we don't really need avatar downloads tbh. Don't worry about lint, I can run it locally once your PR is all set to go. Just added a few tiny comments then we can :shipit:

2024-07-10 01:46 UTC, lowtorola commented on frontend2/src/components/tables/submissions/SubHistoryTable.tsx
> +// TODO: should i pass episodeId down as a prop?
No need to pass `episodeId` down, you can access it anywhere in the App tree using the `useEpisodeId` hook! :sunglasses:

2024-07-10 01:46 UTC, lowtorola commented on frontend2/src/components/tables/submissions/SubHistoryTable.tsx
> +  // downloadSubmission,
nit: remove?

2024-07-10 01:46 UTC, lowtorola commented on frontend2/src/components/tables/submissions/SubHistoryTable.tsx
> +          value: (sub) => <button className="text-cyan-600 hover:underline"
nit: I think we have a `Button` component that we should prefer to use for consistent styling

2024-07-10 01:46 UTC, lowtorola commented on frontend2/src/views/Account.tsx
> +                  Resume uploaded! <button className="text-cyan-600 hover:underline"
nit: also prefer `Button`

2024-07-10 01:46 UTC, lowtorola commented on frontend2/src/api/compete/useCompete.ts
> +    mutationKey: competeMutationKeys.acceptScrim({ episodeId }),
I think this should be the "submission download" key!

2024-09-26 03:11 UTC, lowtorola approved these changes
LGTM! :shipit:

2024-09-26 03:11 UTC, merged